version: '3'

services:
  redis1:
    hostname: redis1
    container_name: redis1
    image: redis
    network_mode: "host"
    command: redis-server /etc/redis.conf
    volumes:
    - ./6300/redis.conf:/etc/redis.conf
    ports:
    - 6300:6300
    - 16300:16300

  redis2:
    hostname: redis2
    container_name: redis2
    image: redis
    network_mode: "host"
    command: redis-server /etc/redis.conf
    volumes:
      - ./6301/redis.conf:/etc/redis.conf
    ports:
      - 6301:6301
      - 16301:16301

  redis3:
    hostname: redis3
    container_name: redis3
    image: redis
    network_mode: "host"
    command: redis-server /etc/redis.conf
    volumes:
      - ./6302/redis.conf:/etc/redis.conf
    ports:
      - 6302:6302
      - 16302:16302

  redis4:
    hostname: redis4
    container_name: redis4
    image: redis
    network_mode: "host"
    command: redis-server /etc/redis.conf
    volumes:
      - ./6400/redis.conf:/etc/redis.conf
    ports:
      - 6400:6400
      - 16400:16400

  redis5:
    hostname: redis5
    container_name: redis5
    image: redis
    network_mode: "host"
    command: redis-server /etc/redis.conf
    volumes:
      - ./6401/redis.conf:/etc/redis.conf
    ports:
      - 6401:6401
      - 16401:16401

  redis6:
    hostname: redis6
    container_name: redis6
    image: redis
    network_mode: "host"
    command: redis-server /etc/redis.conf
    volumes:
      - ./6402/redis.conf:/etc/redis.conf
    ports:
      - 6402:6402
      - 16402:16402
