version: '3.7'

services:
 
  redis-master:
    container_name: master
    image: redis
    command: redis-server --port 6379
    volumes:
     - "./master:/data"
    network_mode: host
    extra_hosts:
      - "redis-master:119.81.23.181"
      - "redis-replica1:119.81.23.181"
      - "redis-replica2:119.81.23.181"
      - "redis-sentinel1:119.81.23.181"
      - "redis-sentinel2:119.81.23.181"
      - "redis-sentinel3:119.81.23.181"
 
  redis-replica1:
    container_name: replica1
    image: redis
    command: redis-server --slaveof redis-master 6379  --replicaof redis-master 6379 --port 6383
    volumes:
     - "./replica1:/data"
    network_mode: host
    extra_hosts:
      - "redis-master:119.81.23.181"
      - "redis-replica1:119.81.23.181"
      - "redis-replica2:119.81.23.181"
      - "redis-sentinel1:119.81.23.181"
      - "redis-sentinel2:119.81.23.181"
      - "redis-sentinel3:119.81.23.181"

  redis-replica2:
    container_name: replica2
    image: redis
    command: redis-server --slaveof redis-master 6379  --replicaof redis-master 6379 --port 6384
    volumes:
     - "./replica2:/data"
    network_mode: host
    extra_hosts:
      - "redis-master:119.81.23.181"
      - "redis-replica1:119.81.23.181"
      - "redis-replica2:119.81.23.181"
      - "redis-sentinel1:119.81.23.181"
      - "redis-sentinel2:119.81.23.181"
      - "redis-sentinel3:119.81.23.181"
     
  # Instance 1
  redis-sentinel1:
    container_name: sentinel1
    build: 
      context: ./sentinel
    ports:
      - "5000:26379"
    extra_hosts:
      - "redis-master:119.81.23.181"
      - "redis-replica1:119.81.23.181"
      - "redis-replica2:119.81.23.181"
      - "redis-sentinel1:119.81.23.181"
      - "redis-sentinel2:119.81.23.181"
      - "redis-sentinel3:119.81.23.181"
 
  # Instance 2
  redis-sentinel2:
    container_name: sentinel2
    build: 
      context: ./sentinel
    links:
      - redis-master
      - redis-replica1
      - redis-replica2
    ports:
      - "5001:26379"
    extra_hosts:
      - "redis-master:119.81.23.181"
      - "redis-replica1:119.81.23.181"
      - "redis-replica2:119.81.23.181"
      - "redis-sentinel1:119.81.23.181"
      - "redis-sentinel2:119.81.23.181"
      - "redis-sentinel3:119.81.23.181"
 
  # Instance 3
  redis-sentinel3:
    container_name: sentinel3
    build: 
      context: ./sentinel
    links:
      - redis-master
      - redis-replica1
      - redis-replica2
    ports:
      - "5002:26379"
    extra_hosts:
      - "redis-master:119.81.23.181"
      - "redis-replica1:119.81.23.181"
      - "redis-replica2:119.81.23.181"
      - "redis-sentinel1:119.81.23.181"
      - "redis-sentinel2:119.81.23.181"
      - "redis-sentinel3:119.81.23.181"
 
 
